<template><div><h1 id="buttoninjection-tests" tabindex="-1"><a class="header-anchor" href="#buttoninjection-tests"><span>ButtonInjection Tests</span></a></h1>
<p>This document provides information about the unit tests and end-to-end (E2E) tests for the <code v-pre>ButtonInjection</code> component.</p>
<h2 id="unit-test" tabindex="-1"><a class="header-anchor" href="#unit-test"><span>Unit Test</span></a></h2>
<p>The unit test checks if the <code v-pre>ButtonInjection</code> component correctly updates the attributes and text of the target button element.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> mount <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@vue/test-utils'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> ButtonInjection <span class="token keyword">from</span> <span class="token string">'../ButtonInjection.vue'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">describe</span><span class="token punctuation">(</span><span class="token string">'ButtonInjection.vue'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">const</span> selector <span class="token operator">=</span> <span class="token punctuation">{</span> attribute<span class="token operator">:</span> <span class="token string">'name'</span><span class="token punctuation">,</span> value<span class="token operator">:</span> <span class="token string">'add'</span> <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> newAttributes <span class="token operator">=</span> <span class="token punctuation">{</span></span>
<span class="line">        id<span class="token operator">:</span> <span class="token string">'new-button-id'</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token keyword">class</span><span class="token operator">:</span> <span class="token string">'new-button-class'</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string-property property">'data-custom'</span><span class="token operator">:</span> <span class="token string">'custom-value'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> text <span class="token operator">=</span> <span class="token string">'New Button Text'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'should update attributes and text of the target element'</span><span class="token punctuation">,</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        document<span class="token punctuation">.</span>body<span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token string">'&lt;button name="add">Old Button Text&lt;/button>'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token function">mount</span><span class="token punctuation">(</span>ButtonInjection<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">            props<span class="token operator">:</span> <span class="token punctuation">{</span> selector<span class="token punctuation">,</span> newAttributes<span class="token punctuation">,</span> text <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">const</span> button <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'button[name="add"]'</span><span class="token punctuation">)</span> <span class="token keyword">as</span> HTMLElement<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>button<span class="token punctuation">)</span><span class="token punctuation">.</span>not<span class="token punctuation">.</span><span class="token function">toBeNull</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>button<span class="token punctuation">.</span><span class="token function">getAttribute</span><span class="token punctuation">(</span><span class="token string">'id'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'new-button-id'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>button<span class="token punctuation">.</span><span class="token function">getAttribute</span><span class="token punctuation">(</span><span class="token string">'class'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'new-button-class'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>button<span class="token punctuation">.</span><span class="token function">getAttribute</span><span class="token punctuation">(</span><span class="token string">'data-custom'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'custom-value'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>button<span class="token punctuation">.</span>innerHTML<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'New Button Text'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="e2e-test" tabindex="-1"><a class="header-anchor" href="#e2e-test"><span>E2E Test</span></a></h2>
<p>The E2E test verifies that the <code v-pre>ButtonInjection</code> component correctly injects content into buttons across the application.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> buttonInjectionContent <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../../src/contentToInject'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">describe</span><span class="token punctuation">(</span><span class="token string">'Button Injector'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">beforeEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">visit</span><span class="token punctuation">(</span><span class="token string">'/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    buttonInjectionContent<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span>button<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token function">it</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">should have the correct attributes and text for the button with \${button.selector.attribute}="\${button.selector.value}"</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">const</span> buttonSelector <span class="token operator">=</span> \`button<span class="token punctuation">[</span>\$<span class="token punctuation">{</span>button<span class="token punctuation">.</span>selector<span class="token punctuation">.</span>attribute<span class="token punctuation">}</span><span class="token operator">=</span><span class="token string">"\${button.selector.value}"</span><span class="token punctuation">]</span>\`<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">            <span class="token comment">// Check that the button exists</span></span>
<span class="line">            cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>buttonSelector<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span><span class="token string">'exist'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">            <span class="token comment">// Check the button text</span></span>
<span class="line">            cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>buttonSelector<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span><span class="token string">'have.text'</span><span class="token punctuation">,</span> button<span class="token punctuation">.</span>content<span class="token punctuation">.</span>translation<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">            <span class="token comment">// Check the button attributes</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span>button<span class="token punctuation">.</span>newAttributes<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                Object<span class="token punctuation">.</span><span class="token function">entries</span><span class="token punctuation">(</span>button<span class="token punctuation">.</span>newAttributes<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">[</span>key<span class="token punctuation">,</span> value<span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">                    cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>buttonSelector<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span><span class="token string">'have.attr'</span><span class="token punctuation">,</span> key<span class="token punctuation">,</span> value<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">                <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>By maintaining a comprehensive suite of tests, we can ensure the reliability and correctness of the <code v-pre>ButtonInjection</code> component.</p>
</div></template>


