<template><div><h1 id="dynamictextinjector-tests" tabindex="-1"><a class="header-anchor" href="#dynamictextinjector-tests"><span>DynamicTextInjector Tests</span></a></h1>
<p>This document provides an overview of the unit and end-to-end (E2E) tests for the <code v-pre>DynamicTextInjector</code> component. The <code v-pre>DynamicTextInjector</code> component dynamically updates a text element based on the value of an input element.</p>
<h2 id="unit-tests" tabindex="-1"><a class="header-anchor" href="#unit-tests"><span>Unit Tests</span></a></h2>
<p>Unit tests are written using Vue Test Utils and Vitest. They verify the functionality of the <code v-pre>DynamicTextInjector</code> component in isolation.</p>
<h3 id="test-file" tabindex="-1"><a class="header-anchor" href="#test-file"><span>Test File</span></a></h3>
<p><strong>Location</strong>: <code v-pre>src/components/__tests__/DynamicTextInjector.spec.ts</code></p>
<h3 id="test-description" tabindex="-1"><a class="header-anchor" href="#test-description"><span>Test Description</span></a></h3>
<h4 id="test-1-renders-the-initial-text-correctly" tabindex="-1"><a class="header-anchor" href="#test-1-renders-the-initial-text-correctly"><span>Test 1: Renders the initial text correctly</span></a></h4>
<ul>
<li><strong>Description</strong>: This test checks if the <code v-pre>DynamicTextInjector</code> component renders the initial text correctly with the placeholder replaced by the calculated value.</li>
<li><strong>Test Code</strong>:</li>
</ul>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> mount <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@vue/test-utils'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> describe<span class="token punctuation">,</span> it<span class="token punctuation">,</span> expect<span class="token punctuation">,</span> beforeEach <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'vitest'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> DynamicTextInjector <span class="token keyword">from</span> <span class="token string">'../DynamicTextInjector.vue'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">describe</span><span class="token punctuation">(</span><span class="token string">'DynamicTextInjector'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">let</span> mockInput<span class="token operator">:</span> HTMLInputElement<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">beforeEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        document<span class="token punctuation">.</span>body<span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string"></span>
<span class="line">      &lt;input class="sc-bnOPBZ bwJNhh pf-43_" min="1" max="50" type="number" </span>
<span class="line">             data-hidespinner="false" name="quantity" data-variants-continue="" </span>
<span class="line">             data-pf-type="QuantityField" value="1"></span>
<span class="line">    </span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span></span>
<span class="line">        mockInput <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span></span>
<span class="line">            <span class="token string">'input[data-pf-type="QuantityField"]'</span></span>
<span class="line">        <span class="token punctuation">)</span> <span class="token keyword">as</span> HTMLInputElement<span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'renders the initial text correctly'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">const</span> wrapper <span class="token operator">=</span> <span class="token function">mount</span><span class="token punctuation">(</span>DynamicTextInjector<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">            props<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">                text<span class="token operator">:</span></span>
<span class="line">                    <span class="token string">'Please select between 1 and 5 products: Current total {count} more items'</span><span class="token punctuation">,</span></span>
<span class="line">                dynamicPlaceholder<span class="token operator">:</span> <span class="token string">'{count}'</span><span class="token punctuation">,</span></span>
<span class="line">                maxCount<span class="token operator">:</span> <span class="token number">5</span><span class="token punctuation">,</span></span>
<span class="line">                linkedInput<span class="token operator">:</span> <span class="token punctuation">{</span> selector<span class="token operator">:</span> <span class="token string">'data-pf-type'</span><span class="token punctuation">,</span> value<span class="token operator">:</span> <span class="token string">'QuantityField'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>wrapper<span class="token punctuation">.</span><span class="token function">text</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toContain</span><span class="token punctuation">(</span><span class="token string">'Current total 4 more items'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'updates the text when input value changes'</span><span class="token punctuation">,</span> <span class="token keyword">async</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">const</span> wrapper <span class="token operator">=</span> <span class="token function">mount</span><span class="token punctuation">(</span>DynamicTextInjector<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">            props<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">                text<span class="token operator">:</span></span>
<span class="line">                    <span class="token string">'Please select between 1 and 5 products: Current total {count} more items'</span><span class="token punctuation">,</span></span>
<span class="line">                dynamicPlaceholder<span class="token operator">:</span> <span class="token string">'{count}'</span><span class="token punctuation">,</span></span>
<span class="line">                maxCount<span class="token operator">:</span> <span class="token number">5</span><span class="token punctuation">,</span></span>
<span class="line">                linkedInput<span class="token operator">:</span> <span class="token punctuation">{</span> selector<span class="token operator">:</span> <span class="token string">'data-pf-type'</span><span class="token punctuation">,</span> value<span class="token operator">:</span> <span class="token string">'QuantityField'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// Simulate changing the input value</span></span>
<span class="line">        mockInput<span class="token punctuation">.</span>value <span class="token operator">=</span> <span class="token string">'2'</span><span class="token punctuation">;</span></span>
<span class="line">        mockInput<span class="token punctuation">.</span><span class="token function">dispatchEvent</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Event</span><span class="token punctuation">(</span><span class="token string">'input'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// Wait for Vue to update the DOM</span></span>
<span class="line">        <span class="token keyword">await</span> wrapper<span class="token punctuation">.</span>vm<span class="token punctuation">.</span><span class="token function">$nextTick</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>wrapper<span class="token punctuation">.</span><span class="token function">text</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toContain</span><span class="token punctuation">(</span><span class="token string">'Current total 3 more items'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="e2e-tests" tabindex="-1"><a class="header-anchor" href="#e2e-tests"><span>E2E Tests</span></a></h2>
<p>E2E tests are written using Cypress. They verify the functionality of the <code v-pre>DynamicTextInjector</code> component in a real browser environment by simulating user interactions.</p>
<h3 id="test-file-1" tabindex="-1"><a class="header-anchor" href="#test-file-1"><span>Test File</span></a></h3>
<p><strong>Location</strong>: <code v-pre>cypress/e2e/dynamicTextInjector.cy.ts</code></p>
<h3 id="test-description-1" tabindex="-1"><a class="header-anchor" href="#test-description-1"><span>Test Description</span></a></h3>
<h4 id="test-1-renders-the-initial-text-correctly-1" tabindex="-1"><a class="header-anchor" href="#test-1-renders-the-initial-text-correctly-1"><span>Test 1: Renders the initial text correctly</span></a></h4>
<ul>
<li><strong>Description</strong>: This test checks if the <code v-pre>DynamicTextInjector</code> component renders the initial text correctly with the placeholder replaced by the calculated value.</li>
<li><strong>Test Code</strong>:</li>
</ul>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token function">describe</span><span class="token punctuation">(</span><span class="token string">'DynamicTextInjector E2E Test'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">beforeEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">visit</span><span class="token punctuation">(</span><span class="token string">'/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'renders the initial text correctly'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'p[data-test="dynamicTextInjection"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span></span>
<span class="line">            <span class="token string">'contain.text'</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">'Aktuelle Gesamtmenge 4 weitere Artikel'</span></span>
<span class="line">        <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'updates the text when input value changes'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// Change input value to 2</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'input[data-pf-type="QuantityField"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">clear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'input[data-pf-type="QuantityField"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">type</span><span class="token punctuation">(</span><span class="token string">'2'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'p[data-test="dynamicTextInjection"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span></span>
<span class="line">            <span class="token string">'contain.text'</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">'Aktuelle Gesamtmenge 3 weitere Artikel'</span></span>
<span class="line">        <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// Change input value to 5</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'input[data-pf-type="QuantityField"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">clear</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'input[data-pf-type="QuantityField"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">type</span><span class="token punctuation">(</span><span class="token string">'5'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'p[data-test="dynamicTextInjection"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span></span>
<span class="line">            <span class="token string">'contain.text'</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">'Aktuelle Gesamtmenge 0 weitere Artikel'</span></span>
<span class="line">        <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="running-the-tests" tabindex="-1"><a class="header-anchor" href="#running-the-tests"><span>Running the Tests</span></a></h2>
<h3 id="running-unit-tests" tabindex="-1"><a class="header-anchor" href="#running-unit-tests"><span>Running Unit Tests</span></a></h3>
<p>To run the unit tests, use the following command:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> run test:unit</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="running-e2e-tests" tabindex="-1"><a class="header-anchor" href="#running-e2e-tests"><span>Running E2E Tests</span></a></h3>
<p>To run the E2E tests, use the following command:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> run test:e2e</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>To run the E2E tests in development mode, use the following command:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> run test:e2e:dev</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>By maintaining a comprehensive suite of tests, we can ensure the reliability and correctness of the <code v-pre>DynamicTextInjector</code> component.</p>
</div></template>


