<template><div><h1 id="textinjector-tests" tabindex="-1"><a class="header-anchor" href="#textinjector-tests"><span>TextInjector Tests</span></a></h1>
<p>This document provides an overview of the unit and end-to-end (E2E) tests for the <code v-pre>TextInjector</code> component. The <code v-pre>TextInjector</code> component is responsible for injecting text and attributes into an existing HTML element.</p>
<h2 id="unit-tests" tabindex="-1"><a class="header-anchor" href="#unit-tests"><span>Unit Tests</span></a></h2>
<p>Unit tests are written using Vue Test Utils and Jest. They verify the functionality of the <code v-pre>TextInjector</code> component in isolation.</p>
<h3 id="test-file" tabindex="-1"><a class="header-anchor" href="#test-file"><span>Test File</span></a></h3>
<p><strong>Location</strong>: <code v-pre>src/components/__tests__/TextInjector.spec.ts</code></p>
<h3 id="test-description" tabindex="-1"><a class="header-anchor" href="#test-description"><span>Test Description</span></a></h3>
<h4 id="test-1-creates-a-new-element-with-the-same-attributes-and-updated-text" tabindex="-1"><a class="header-anchor" href="#test-1-creates-a-new-element-with-the-same-attributes-and-updated-text"><span>Test 1: Creates a new element with the same attributes and updated text</span></a></h4>
<ul>
<li><strong>Description</strong>: This test checks if the <code v-pre>TextInjector</code> component creates a new element with the same attributes as the original element and updates the text content.</li>
<li><strong>Test Code</strong>:</li>
</ul>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> mount <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@vue/test-utils'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> TextInjector <span class="token keyword">from</span> <span class="token string">'../TextInjector.vue'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">describe</span><span class="token punctuation">(</span><span class="token string">'TextInjector.vue'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'Creates a new element with the same attributes and updated text'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// Create a mock element</span></span>
<span class="line">        <span class="token keyword">const</span> mockElement <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">'h3'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'class'</span><span class="token punctuation">,</span> <span class="token string">'insert-sick-styling-here'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'data-test'</span><span class="token punctuation">,</span> <span class="token string">'test-me'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token string">"I'm a heading!"</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// Mount the component with the mock element and translated text</span></span>
<span class="line">        <span class="token keyword">const</span> wrapper <span class="token operator">=</span> <span class="token function">mount</span><span class="token punctuation">(</span>TextInjector<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">            props<span class="token operator">:</span> <span class="token punctuation">{</span> text<span class="token operator">:</span> <span class="token string">'Test Text'</span><span class="token punctuation">,</span> el<span class="token operator">:</span> mockElement <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">const</span> renderedElement <span class="token operator">=</span> wrapper<span class="token punctuation">.</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token string">'h3'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">exists</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">text</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'Test Text'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'class'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'insert-sick-styling-here'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'data-test'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'test-me'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">"Updates and add's attributes"</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token comment">// Create a mock element</span></span>
<span class="line">        <span class="token keyword">const</span> mockElement <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">createElement</span><span class="token punctuation">(</span><span class="token string">'button'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'data-soldout'</span><span class="token punctuation">,</span> <span class="token string">'Sold Out'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'data-adding'</span><span class="token punctuation">,</span> <span class="token string">'Adding...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'data-added'</span><span class="token punctuation">,</span> <span class="token string">'Thank you!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'type'</span><span class="token punctuation">,</span> <span class="token string">'button'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span><span class="token function">setAttribute</span><span class="token punctuation">(</span><span class="token string">'name'</span><span class="token punctuation">,</span> <span class="token string">'add'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        mockElement<span class="token punctuation">.</span>innerHTML <span class="token operator">=</span> <span class="token string">'Add to Cart'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token comment">// Mount the component with the mock element and changed attributes</span></span>
<span class="line">        <span class="token keyword">const</span> wrapper <span class="token operator">=</span> <span class="token function">mount</span><span class="token punctuation">(</span>TextInjector<span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">            props<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">                text<span class="token operator">:</span> <span class="token string">'In den Warenkorb'</span><span class="token punctuation">,</span></span>
<span class="line">                el<span class="token operator">:</span> mockElement<span class="token punctuation">,</span></span>
<span class="line">                newAttributes<span class="token operator">:</span> <span class="token punctuation">{</span></span>
<span class="line">                    <span class="token string-property property">'data-soldout'</span><span class="token operator">:</span> <span class="token string">'Ausverkauft'</span><span class="token punctuation">,</span></span>
<span class="line">                    <span class="token string-property property">'data-adding'</span><span class="token operator">:</span> <span class="token string">'Füge hinzu...'</span><span class="token punctuation">,</span></span>
<span class="line">                    <span class="token string-property property">'data-added'</span><span class="token operator">:</span> <span class="token string">'Dankeschön!'</span><span class="token punctuation">,</span></span>
<span class="line">                <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        <span class="token keyword">const</span> renderedElement <span class="token operator">=</span> wrapper<span class="token punctuation">.</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token string">'button'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">exists</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">text</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'In den Warenkorb'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'data-soldout'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'Ausverkauft'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'data-adding'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'Füge hinzu...'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'data-added'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'Dankeschön!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'type'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'button'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token function">expect</span><span class="token punctuation">(</span>renderedElement<span class="token punctuation">.</span><span class="token function">attributes</span><span class="token punctuation">(</span><span class="token string">'name'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toBe</span><span class="token punctuation">(</span><span class="token string">'add'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="e2e-tests" tabindex="-1"><a class="header-anchor" href="#e2e-tests"><span>E2E Tests</span></a></h2>
<p>E2E tests are written using Cypress. They verify the functionality of the <code v-pre>TextInjector</code> component in a real browser environment by simulating user interactions.</p>
<h3 id="test-file-1" tabindex="-1"><a class="header-anchor" href="#test-file-1"><span>Test File</span></a></h3>
<p><strong>Location</strong>: <code v-pre>cypress/e2e/textInjection_spec.cy.ts</code></p>
<h3 id="test-description-1" tabindex="-1"><a class="header-anchor" href="#test-description-1"><span>Test Description</span></a></h3>
<h4 id="test-1-injects-translated-text-into-the-headings" tabindex="-1"><a class="header-anchor" href="#test-1-injects-translated-text-into-the-headings"><span>Test 1: Injects translated text into the headings</span></a></h4>
<ul>
<li><strong>Description</strong>: This test checks if the <code v-pre>TextInjector</code> component correctly injects the translated text into the headings with the <code v-pre>data-pf-type=&quot;Heading2&quot;</code> attribute.</li>
<li><strong>Test Code</strong>:</li>
</ul>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts" data-title="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> textInjectionContent <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../../src/contentToInject'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token keyword">type</span> <span class="token punctuation">{</span> ITextInjection <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../../src/types'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">const</span> getTextTranslations <span class="token operator">=</span> <span class="token punctuation">(</span></span>
<span class="line">    dataArray<span class="token operator">:</span> ITextInjection<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line">    targetValue<span class="token operator">:</span> <span class="token builtin">string</span></span>
<span class="line"><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// Filters array of objects for the targetValue</span></span>
<span class="line">    <span class="token keyword">const</span> filterForValue <span class="token operator">=</span> dataArray<span class="token punctuation">.</span><span class="token function">filter</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token punctuation">(</span>item<span class="token operator">:</span> ITextInjection<span class="token punctuation">)</span> <span class="token operator">=></span> item<span class="token punctuation">.</span>selector<span class="token punctuation">.</span>value <span class="token operator">===</span> targetValue</span>
<span class="line">    <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token comment">// Creates a new array of strings, only containing the translations</span></span>
<span class="line">    <span class="token keyword">const</span> createTranslationArray <span class="token operator">=</span> filterForValue<span class="token punctuation">.</span><span class="token function">map</span><span class="token punctuation">(</span><span class="token punctuation">(</span>el<span class="token punctuation">)</span> <span class="token operator">=></span> el<span class="token punctuation">.</span>content<span class="token punctuation">.</span>translation<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">return</span> createTranslationArray<span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">describe</span><span class="token punctuation">(</span><span class="token string">'Text Injector'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function">beforeEach</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">visit</span><span class="token punctuation">(</span><span class="token string">'/'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'injects translated text into the headings'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">const</span> expectedTranslations <span class="token operator">=</span> <span class="token function">getTextTranslations</span><span class="token punctuation">(</span></span>
<span class="line">            textInjectionContent<span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">'Heading2'</span></span>
<span class="line">        <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'h3[data-pf-type="Heading2"]'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">each</span><span class="token punctuation">(</span><span class="token punctuation">(</span>$el<span class="token punctuation">,</span> index<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span>index <span class="token operator">&lt;</span> expectedTranslations<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                cy<span class="token punctuation">.</span><span class="token function">wrap</span><span class="token punctuation">(</span>$el<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span><span class="token string">'have.html'</span><span class="token punctuation">,</span> expectedTranslations<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'injects translated text into the paragraphs'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">const</span> expectedTranslations <span class="token operator">=</span> <span class="token function">getTextTranslations</span><span class="token punctuation">(</span></span>
<span class="line">            textInjectionContent<span class="token punctuation">,</span></span>
<span class="line">            <span class="token string">'Paragraph3'</span></span>
<span class="line">        <span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">        cy<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'p[data-pf-type="Paragraph3"'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">each</span><span class="token punctuation">(</span><span class="token punctuation">(</span>$el<span class="token punctuation">,</span> index<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">            <span class="token keyword">if</span> <span class="token punctuation">(</span>index <span class="token operator">&lt;</span> expectedTranslations<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                cy<span class="token punctuation">.</span><span class="token function">wrap</span><span class="token punctuation">(</span>$el<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">should</span><span class="token punctuation">(</span><span class="token string">'have.html'</span><span class="token punctuation">,</span> expectedTranslations<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">            <span class="token punctuation">}</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="running-the-tests" tabindex="-1"><a class="header-anchor" href="#running-the-tests"><span>Running the Tests</span></a></h2>
<h3 id="running-unit-tests" tabindex="-1"><a class="header-anchor" href="#running-unit-tests"><span>Running Unit Tests</span></a></h3>
<p>To run the unit tests, use the following command:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> run test:unit</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="running-e2e-tests" tabindex="-1"><a class="header-anchor" href="#running-e2e-tests"><span>Running E2E Tests</span></a></h3>
<p>To run the E2E tests, use the following command:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> run test:e2e</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>To run the E2E tests in development mode, use the following command:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh" data-title="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> run test:e2e:dev</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>By maintaining a comprehensive suite of tests, we can ensure the reliability and correctness of the <code v-pre>TextInjector</code> component.</p>
</div></template>


